version: '3'
services:
  mysite:
    build: .
    container_name: misitio
    networks:
      - grid
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      - SELENIUM_REMOTE_HOST=selenium-chrome
  selenium-chrome:
    image: selenium/standalone-chrome
    shm_size: 2gb
    networks:
      - grid
    ports:
      - 4444:4444
    depends_on:
      - mysite

networks:
  grid:
    driver: bridge
