version: '2'
services:
  mysite:
    build: .
    ports:
      - 8080:8080
      - 9990:9990
  selenium-hub:
    image: selenium/hub
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    depends_on:
      - mysite
  selenium-chrome:
    image: selenium/node-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - 6900:5900
