services:
  mysite:
    build: .
    container_name: misitio
    ports:
      - 8080:8080
      - 9990:9990
  selenium:
    images: selenium/standalone-chrome
    ports:
      - 4444:4444
    depend_on:
      - mysite
