version: '3'
services:
  mysite:
    build: .
    container_name: misitio
    networks:
      - grid
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_REMOTE_HOST=selenium-chrome
      - BROWSERSTACK_USERNAME= "alfredoayalaorte_MB2SFH"
      - BROWSERSTACK_ACCESS_KEY= "Rg48u7zQz7PvkfW6hsyq"
      - BROWSERSTACK_LOCAL= false
      - BROWSERSTACK_LOCAL_IDENTIFIER= "identifier"
  selenium-chrome:
    image: selenium/standalone-chrome
    shm_size: 2gb
    networks:
      - grid
    ports:
      - 4444:4444
networks:
  grid:
    driver: bridge
