version:2
jobs:
	build:
		working_directory: /MySite
		docker:
			- image: docker:17.05.0-ce-git
		steps:
			- checkout
			- set_up_remote_docker
			- run:
				name: Install Dependencies
				command: |
					apk add --no-cache py-pip=9.0.0-r1
					pip install docker-compose==1.15.0
			- run:
				name: Run test
				command: |
					docker-compose up -d
					docker-compose run misitio pyton /opt/jboss/wildfly/welcome-content/test.py