version: 2

test:
    pre:
    # Download the browserstack binary file
    - wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
    # Unzip the BrowserStack Local binary file
    - unzip BrowserStackLocal-linux-x64.zip
    # Run the file with your access key
    - ./BrowserStackLocal $BROWSERSTACK_ACCESS_KEY:
        background: true
        
jobs:
  build:
    working_directory: /MySite
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          BROWSERSTACK_USERNAME: "alfredoayalaorte_MB2SFH"
          BROWSERSTACK_ACCESS_KEY: "Rg48u7zQz7PvkfW6hsyq"
          BROWSERSTACK_LOCAL: false
          BROWSERSTACK_LOCAL_IDENTIFIER: "identifier"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
            pip install selenium==3.141.0
      - run:
          name: Run test
          command: |
            docker-compose up -d
            docker inspect mysite_selenium-chrome_1
            docker inspect misitio
            python test.py